from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import TaskViewSet

# Routers automatically generate URL routes for your ViewSets
router = DefaultRouter()

# 'tasks' will be the URL prefix (e.g., /tasks/)
router.register(r'tasks', TaskViewSet)

# Define the urlpatterns
urlpatterns = [
    # Include all the routes generated by the router
    path('', include(router.urls)),
]
