# Generated by Django 5.2.5 on 2025-09-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Normal', 'Normal')], default='Normal', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(default='General', max_length=100)),
            ],
        ),
    ]
